config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('user/', include('users.urls', namespace='user')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    MailingAttemptListView, ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    index, BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, set_mailing_status_disregard

app_name = MainConfig.name

urlpatterns = [
    path('', index, name='home'),
    path('mailings/', MailingListView.as_view(), name='mailings'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/new/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/<int:pk>/edit/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('attempts/', MailingAttemptListView.as_view(), name='attempts'),
    path('clients/', ClientListView.as_view(), name='clients'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/new/', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/edit/', ClientUpdateView.as_view(), name='client_edit'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('blog', cache_page(60)(BlogListView.as_view()), name='blog'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/new/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/edit/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
    path('mailings/disregard/<int:mailing_id>/', set_mailing_status_disregard, name='disregard_mailing'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from main.urls import urlpatterns as main_url
from main.apps import MainConfig
from users.views import register, verify_email, CustomLoginView, ProfileUpdateView, PasswordResetView, UserListView, \
    UserDetailsView, toggle_user_active

app_name = MainConfig.name

urlpatterns = [
                  path('register/', register, name='register'),
                  path('verify-email/<uuid:token>/', verify_email, name='verify_email'),
                  path('login/', CustomLoginView.as_view(), name='login'),
                  path('logout/', LogoutView.as_view(), name='logout'),
                  path('edit_profile/', ProfileUpdateView.as_view(), name='edit_profile'),
                  path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
                  path('users/', UserListView.as_view(), name='users'),
                  path('users/<int:pk>/', UserDetailsView.as_view(), name='user_detail'),
                  path('users/toggle/<int:user_id>/', toggle_user_active, name='user_toggle'),
              ] + main_url

users/models.py
import uuid

from django.apps import apps
from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models

NULLABLE = {
    'blank': True,
    'null': True
}


class UserManager(BaseUserManager):
    """
    Менеджер пользователей для модели User, поддерживающий создание обычных пользователей и суперпользователей.

    Атрибуты:
    ----------
    use_in_migrations : bool
        Определяет, может ли этот менеджер быть использован в миграциях.

    Методы:
    -------
    _create_user(email, password, **extra_fields):
        Внутренний метод для создания и сохранения пользователя с заданным email и паролем.

    create_user(email, password=None, **extra_fields):
        Создает и сохраняет обычного пользователя с заданным email и паролем.

    create_superuser(email, password=None, **extra_fields):
        Создает и сохраняет суперпользователя с заданным email и паролем.

    Описание методов:
    -----------------
    _create_user(email, password, **extra_fields):
        Этот метод выполняет основную логику создания и сохранения пользователя. Проверяет наличие email, нормализует
        его, создает экземпляр модели пользователя, устанавливает пароль и сохраняет пользователя в базе данных.

        Параметры:
        - email (str): Электронная почта пользователя.
        - password (str): Пароль пользователя.
        - **extra_fields: Прочие поля, которые необходимо установить для пользователя.

        Исключения:
        - ValueError: Если email не указан.

    create_user(email, password=None, **extra_fields):
        Этот метод используется для создания обычного пользователя. Он вызывает внутренний метод `_create_user`,
        устанавливая флаги `is_staff` и `is_superuser` в False.

        Параметры:
        - email (str): Электронная почта пользователя.
        - password (str, optional): Пароль пользователя. По умолчанию None.
        - **extra_fields: Прочие поля, которые необходимо установить для пользователя.

    create_superuser(email, password=None, **extra_fields):
        Этот метод используется для создания суперпользователя. Он вызывает внутренний метод `_create_user`,
        устанавливая флаги `is_staff` и `is_superuser` в True. Также проверяет, что эти флаги действительно установлены
        в True.

        Параметры:
        - email (str): Электронная почта пользователя.
        - password (str, optional): Пароль пользователя. По умолчанию None.
        - **extra_fields: Прочие поля, которые необходимо установить для пользователя.

        Исключения:
        - ValueError: Если `is_staff` не установлен в True.
        - ValueError: Если `is_superuser` не установлен в True.
    """

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given username must be set")

        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """
    Модель пользователя с использованием электронной почты в качестве логина

    Поля:
        - email: Электронная почта. Уникальное поле.
        - is_email_verified: Флаг подтверждения электронной почты. По умолчанию False.
        - email_verification_token: Токен для подтверждения электронной почты. Генерируется автоматически.
        - first_name: Имя пользователя. Максимальная длина 50 символов. Может быть пустым.
        - last_name: Фамилия пользователя. Максимальная длина 50 символов. Может быть пустым.

    Специальные атрибуты:
        - USERNAME_FIELD: Поле, используемое в качестве логина (в данном случае 'email').
        - REQUIRED_FIELDS: Обязательные поля для создания суперпользователя (пусто).

    Методы:
        - str(self): Возвращает строковое представление пользователя.
        - get_full_name(self): Возвращает полное имя пользователя.
        - send_verification_email(self): Отправляет письмо для подтверждения электронной почты.
        - save(self, *args, **kwargs): Переопределяет метод сохранения, отправляя письмо для подтверждения электронной
                                       почты при создании нового пользователя.

    Классы:
        - Meta:
            - permissions: Дополнительные права для модели. В данном случае, право блокировать пользователей сервиса
                           ('set_active').

    Описание:
        Эта модель расширяет стандартную модель пользователя, используемую в Django, с заменой имени пользователя
        на электронную почту.
    """

    username = None
    email = models.EmailField(verbose_name='Почта', unique=True)
    is_email_verified = models.BooleanField(default=False, verbose_name='Почта подтверждена')
    email_verification_token = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    first_name = models.CharField(max_length=50, verbose_name='Имя', **NULLABLE)
    last_name = models.CharField(max_length=50, verbose_name='Фамилия', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        permissions = [
            (
                'set_active',
                'Может блокировать пользователей сервиса.'
            )
        ]

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def send_verification_email(self):
        """
        Отправка письма для подтверждения электронной почты

        Описание:
            Этот метод создает URL для подтверждения электронной почты и отправляет его на указанный электронный адрес.
        """

        verification_url = f'{settings.SITE_URL}/user/verify-email/{self.email_verification_token}/'
        subject = 'Verify your email address'
        message = f'Please verify your email address by clicking the following link: {verification_url}'
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [self.email])

        print('message sent')

    def save(self, *args, **kwargs):
        """
        Сохранение модели пользователя

        Описание:
            Переопределяет метод сохранения модели, отправляя письмо для подтверждения электронной почты при создании
            нового пользователя.

        Параметры:
            - args: Дополнительные позиционные аргументы.
            - kwargs: Дополнительные именованные аргументы.
        """

        is_new = self._state.adding

        super().save(*args, **kwargs)

        if is_new:
            self.send_verification_email()

main/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget, AdminTimeWidget

from .models import Mailing, Client


class MailingForm(forms.ModelForm):
    """
    Форма для создания и обновления экземпляров модели Mailing.

    Атрибуты:
        scheduled_time (forms.DateTimeField): Поле для указания даты и времени отправки, отображается как ввод типа
                                              datetime-local.
    """

    scheduled_time = forms.DateTimeField(label='Дата и время отправки',
                                         widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    class Meta:
        model = Mailing
        fields = [
            'title',
            'message',
            'status',
            'scheduled_time',
            'periodicity',
            'clients'
        ]


class ClientForm(forms.ModelForm):
    """
    Форма для создания и обновления экземпляров модели Client.

    Атрибуты (из Meta-класса):
        email (forms.EmailField): Поле для ввода email адреса клиента.
        last_name (forms.CharField): Поле для ввода фамилии клиента.
        first_name (forms.CharField): Поле для ввода имени клиента.
        second_name (forms.CharField): Поле для ввода отчества клиента.
        comment (forms.CharField): Поле для ввода комментария о клиенте.
    """

    class Meta:
        model = Client
        fields = ['email', 'last_name', 'first_name', 'second_name', 'comment']

main/templates/main/include/inc_footer.html
{% load static %}
<footer class="footer mt-auto d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top mx-3">
    <p class="col-md-2 mb-0 text-body-secondary">2024 - {% now "Y" %}, Кудряшов Р.О.</p>
    {% include 'main/include/inc_menu.html' %}
</footer>

main/templates/main/include/inc_header.html
{% load static %}
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom mx-3">
    <div class="col-md-3 mb-2 mb-md-0">
        <a href="/"
           class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <img class="bi me-2" width="40" height="32" src="{% static 'main/favicons/favicon-32x32.png' %}"/>
            <span class="fs-4">Сервис управления рассылками</span>
        </a>
    </div>
    {% include 'main/include/inc_menu.html' %}
</header>

main/templates/main/include/inc_menu.html
<ul class="nav nav-pills">
    <li>
        <a href="{% url 'main:home' %}" class="nav-link {% if current_url_name == 'home' %}active{% endif %}"
           aria-current="page">Главная</a>
    </li>
    {% if user.is_authenticated and user.is_email_verified %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle {% if current_url_name == 'mailings' or current_url_name == 'mailing_create' %}active{% endif %}"
           href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Рассылка</a>
        <ul class="dropdown-menu">
            <li>
                <a href="{% url 'main:mailings' %}"
                   class="nav-link {% if current_url_name == 'mailings' %}active{% endif %}"
                   aria-current="page">Список рассылок</a>
            </li>
            <li>
                <a href="{% url 'main:mailing_create' %}"
                   class="nav-link {% if current_url_name == 'mailing_create' %}active{% endif %}" aria-current="page">Создать
                    новую рассылку</a>
            </li>
        </ul>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle {% if current_url_name == 'clients' or current_url_name == 'client_create' %}active{% endif %}"
           href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Клиенты</a>
        <ul class="dropdown-menu">
            <li class="nav-item">
                <a href="{% url 'main:clients' %}"
                   class="nav-link {% if current_url_name == 'clients' %}active{% endif %}">Список клиентов</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'main:client_create' %}"
                   class="nav-link {% if current_url_name == 'client_create' %}active{% endif %}">Добавить клиента</a>
            </li>
        </ul>
    </li>
    <li class="nav-item">
        <a href="{% url 'main:attempts' %}" class="nav-link {% if current_url_name == 'attempts' %}active{% endif %}"
           aria-current="page">Результаты
            рассылок</a>
    </li>
    {% endif %}
    <li class="nav-item">
        <a href="{% url 'main:blog' %}" class="nav-link {% if current_url_name == 'blog' %}active{% endif %}">Блог</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a href="{% url 'user:edit_profile' %}"
           class="nav-link {% if current_url_name == 'profile' %}active{% endif %}">Профиль</a>
    </li>
    {% if user.is_superuser %}
    <li class="nav-item">
        <a href="{% url 'admin:index' %}" class="nav-link">Админка</a>
    </li>
    {% endif %}
    {% if perms.users.view_user %}
    <li class="nav-item">
        <a href="{% url 'user:users' %}" class="nav-link {% if current_url_name == 'users' %}active{% endif %}">
            Пользователи</a>
    </li>
    {% endif %}
    <li class="nav-item">
        <form method="post" action="{% url 'user:logout' %}">
            {% csrf_token %}
            <button type="submit" class="nav-link">Выход</button>
        </form>
    </li>
    {% else %}
    <li class="nav-item">
        <a href="{% url 'user:login' %}"
           class="nav-link {% if current_url_name == 'login' %}active{% endif %}">Войти</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'user:register' %}" class="nav-link {% if current_url_name == 'register' %}active{% endif %}">Регистрация</a>
    </li>
    {% endif %}
</ul>