config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('user/', include('users.urls', namespace='user')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    MailingAttemptListView, ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    index, BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, set_mailing_status_disregard

app_name = MainConfig.name

urlpatterns = [
    path('', index, name='home'),
    path('mailings/', MailingListView.as_view(), name='mailings'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/new/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/<int:pk>/edit/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('attempts/', MailingAttemptListView.as_view(), name='attempts'),
    path('clients/', ClientListView.as_view(), name='clients'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/new/', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/edit/', ClientUpdateView.as_view(), name='client_edit'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('blog', cache_page(60)(BlogListView.as_view()), name='blog'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/new/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/edit/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
    path('mailings/disregard/<int:mailing_id>/', set_mailing_status_disregard, name='disregard_mailing'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from main.urls import urlpatterns as main_url
from main.apps import MainConfig
from users.views import register, verify_email, CustomLoginView, ProfileUpdateView, PasswordResetView, UserListView, \
    UserDetailsView, toggle_user_active

app_name = MainConfig.name

urlpatterns = [
                  path('register/', register, name='register'),
                  path('verify-email/<uuid:token>/', verify_email, name='verify_email'),
                  path('login/', CustomLoginView.as_view(), name='login'),
                  path('logout/', LogoutView.as_view(), name='logout'),
                  path('edit_profile/', ProfileUpdateView.as_view(), name='edit_profile'),
                  path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
                  path('users/', UserListView.as_view(), name='users'),
                  path('users/<int:pk>/', UserDetailsView.as_view(), name='user_detail'),
                  path('users/toggle/<int:user_id>/', toggle_user_active, name='user_toggle'),
              ] + main_url

users/models.py
import uuid

from django.apps import apps
from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models

NULLABLE = {
    'blank': True,
    'null': True
}


class UserManager(BaseUserManager):
    """
    Менеджер пользователей для модели User, поддерживающий создание обычных пользователей и суперпользователей.

    Атрибуты:
    ----------
    use_in_migrations : bool
        Определяет, может ли этот менеджер быть использован в миграциях.

    Методы:
    -------
    _create_user(email, password, **extra_fields):
        Внутренний метод для создания и сохранения пользователя с заданным email и паролем.

    create_user(email, password=None, **extra_fields):
        Создает и сохраняет обычного пользователя с заданным email и паролем.

    create_superuser(email, password=None, **extra_fields):
        Создает и сохраняет суперпользователя с заданным email и паролем.

    Описание методов:
    -----------------
    _create_user(email, password, **extra_fields):
        Этот метод выполняет основную логику создания и сохранения пользователя. Проверяет наличие email, нормализует
        его, создает экземпляр модели пользователя, устанавливает пароль и сохраняет пользователя в базе данных.

        Параметры:
        - email (str): Электронная почта пользователя.
        - password (str): Пароль пользователя.
        - **extra_fields: Прочие поля, которые необходимо установить для пользователя.

        Исключения:
        - ValueError: Если email не указан.

    create_user(email, password=None, **extra_fields):
        Этот метод используется для создания обычного пользователя. Он вызывает внутренний метод `_create_user`,
        устанавливая флаги `is_staff` и `is_superuser` в False.

        Параметры:
        - email (str): Электронная почта пользователя.
        - password (str, optional): Пароль пользователя. По умолчанию None.
        - **extra_fields: Прочие поля, которые необходимо установить для пользователя.

    create_superuser(email, password=None, **extra_fields):
        Этот метод используется для создания суперпользователя. Он вызывает внутренний метод `_create_user`,
        устанавливая флаги `is_staff` и `is_superuser` в True. Также проверяет, что эти флаги действительно установлены
        в True.

        Параметры:
        - email (str): Электронная почта пользователя.
        - password (str, optional): Пароль пользователя. По умолчанию None.
        - **extra_fields: Прочие поля, которые необходимо установить для пользователя.

        Исключения:
        - ValueError: Если `is_staff` не установлен в True.
        - ValueError: Если `is_superuser` не установлен в True.
    """

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given username must be set")

        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """
    Модель пользователя с использованием электронной почты в качестве логина

    Поля:
        - email: Электронная почта. Уникальное поле.
        - is_email_verified: Флаг подтверждения электронной почты. По умолчанию False.
        - email_verification_token: Токен для подтверждения электронной почты. Генерируется автоматически.
        - first_name: Имя пользователя. Максимальная длина 50 символов. Может быть пустым.
        - last_name: Фамилия пользователя. Максимальная длина 50 символов. Может быть пустым.

    Специальные атрибуты:
        - USERNAME_FIELD: Поле, используемое в качестве логина (в данном случае 'email').
        - REQUIRED_FIELDS: Обязательные поля для создания суперпользователя (пусто).

    Методы:
        - str(self): Возвращает строковое представление пользователя.
        - get_full_name(self): Возвращает полное имя пользователя.
        - send_verification_email(self): Отправляет письмо для подтверждения электронной почты.
        - save(self, *args, **kwargs): Переопределяет метод сохранения, отправляя письмо для подтверждения электронной
                                       почты при создании нового пользователя.

    Классы:
        - Meta:
            - permissions: Дополнительные права для модели. В данном случае, право блокировать пользователей сервиса
                           ('set_active').

    Описание:
        Эта модель расширяет стандартную модель пользователя, используемую в Django, с заменой имени пользователя
        на электронную почту.
    """

    username = None
    email = models.EmailField(verbose_name='Почта', unique=True)
    is_email_verified = models.BooleanField(default=False, verbose_name='Почта подтверждена')
    email_verification_token = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    first_name = models.CharField(max_length=50, verbose_name='Имя', **NULLABLE)
    last_name = models.CharField(max_length=50, verbose_name='Фамилия', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        permissions = [
            (
                'set_active',
                'Может блокировать пользователей сервиса.'
            )
        ]

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def send_verification_email(self):
        """
        Отправка письма для подтверждения электронной почты

        Описание:
            Этот метод создает URL для подтверждения электронной почты и отправляет его на указанный электронный адрес.
        """

        verification_url = f'{settings.SITE_URL}/user/verify-email/{self.email_verification_token}/'
        subject = 'Verify your email address'
        message = f'Please verify your email address by clicking the following link: {verification_url}'
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [self.email])

        print('message sent')

    def save(self, *args, **kwargs):
        """
        Сохранение модели пользователя

        Описание:
            Переопределяет метод сохранения модели, отправляя письмо для подтверждения электронной почты при создании
            нового пользователя.

        Параметры:
            - args: Дополнительные позиционные аргументы.
            - kwargs: Дополнительные именованные аргументы.
        """

        is_new = self._state.adding

        super().save(*args, **kwargs)

        if is_new:
            self.send_verification_email()

users/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField, UsernameField
from django.urls import reverse_lazy

from users.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email', 'first_name', 'last_name')


class ProfileForm(forms.ModelForm):
    """
    Форма для обновления профиля пользователя с функциональностью смены пароля

    Поля:
        - old_password (CharField): Старый пароль пользователя. Отображается как поле ввода пароля.
        - new_password1 (CharField): Новый пароль пользователя. Отображается как поле ввода пароля.
        - new_password2 (CharField): Подтверждение нового пароля пользователя. Отображается как поле ввода пароля.

    Методы:
        - clean(self): Проверяет совпадение нового пароля и его подтверждения.

        Если пароли не совпадают, добавляется соответствующая ошибка в поле 'new_password2'.

    Описание:
        Данная форма позволяет пользователю обновлять свой профиль, включая возможность смены пароля.
    """

    old_password = forms.CharField(widget=forms.PasswordInput, label='Старый пароль')
    new_password1 = forms.CharField(widget=forms.PasswordInput, label='Новый пароль')
    new_password2 = forms.CharField(widget=forms.PasswordInput, label='Подтвердите новый пароль')

    def clean(self):
        """
        Проверка совпадения нового пароля и его подтверждения

        Описание:
            Метод очищает и проверяет данные формы. Если поля 'new_password1' и 'new_password2' не совпадают,
            добавляется ошибка.

        Возвращает:
            dict: Очищенные данные формы.
        """

        cleaned_data = super().clean()

        new_password1 = cleaned_data.get("new_password1")
        new_password2 = cleaned_data.get("new_password2")

        if new_password1 and new_password2 and new_password1 != new_password2:
            self.add_error('new_password2', "Пароли не совпадают")

        return cleaned_data

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')

users/templates/users/edit_profile.html
{% extends 'main/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <h1 class="text-center">Редактирование пользователя</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-outline-light mt-2" type="submit">Сохранить</button>
        </form>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <h1 class="text-center">Вход</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">E-mail:</label>
                <input type="text" class="form-control" name="username" id="username" required>
            </div>
            <div class="form-group">
                <label for="password">Пароль:</label>
                <input type="password" class="form-control" name="password" id="password" required>
            </div>
            <button type="submit" class="btn btn-outline-light mt-2">Войти</button>
            <input type="hidden" name="next" value="{{ next }}">
        </form>
        <form method="get" action="../password_reset/">
            <button class="p-2 btn btn-outline-light mt-2" type="submit">Забыли пароль?</button>
        </form>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'main/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <h1 class="text-center">Смена пароля</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-outline-light mt-2" type="submit">Изменить</button>
        </form>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'main/base.html' %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <form method="post">
            {% csrf_token %}
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" required>
            <button class="p-2 btn btn-outline-light" type="submit">Восстановить пароль</button>
        </form>
        <a class="p-2 btn btn-outline-light mt-2" href="{% url 'user:login' %}">Назад</a>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends 'main/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <h1 class="text-center">Регистрация пользователя</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-outline-light mt-2" type="submit">Зарегистрировать</button>
        </form>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container">
    <div class="card mb-4 rounded-3 shadow-sm text-center">
        <div class="card-header py-3">
            <h4 class="my-0 fw-normal">{{ object.email }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title">{{ object.get_full_name }}</h1>
            <ul class="list-unstyled mt-3 mb-4">
                <li>
                    Статус:
                    {% if object.is_active %}
                    активен
                    {% else %}
                    неактивен
                    {% endif %}
                </li>
            </ul>
            {% if perms.users.change_user %}
            <a href="#" class="btn btn-outline-primary">Редактировать</a>
            {% endif %}
            {% if perms.users.delete_user %}
            <a href="#" class="btn btn-outline-danger">Удалить</a>
            {% endif %}
            {% if perms.users.set_active %}
            <a href="{% url 'user:user_toggle' object.pk %}"
               class="btn btn-outline-{% if object.is_active %}danger{% else %}light{% endif %}">
                {% if object.is_active %}
                Заблокировать
                {% else %}
                Активировать
                {% endif %}
            </a>
            {% endif %}
            <a href="{% url 'user:users' %}" class="btn btn-outline-secondary">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}
{% block content %}
<table class="table table-hover">
    {% for usr in object_list %}
    {% if perms.users.view_user and not usr.is_superuser %}
    <tr>
        <td class="text-end">
            <a href="{% url 'user:user_detail' usr.pk %}" class="action">{{ usr }}</a>
        </td>
        {% if perms.users.change_user %}
        <td>
            <a href="#"
               class="btn btn-outline-light form-control">Редактировать</a>
        </td>
        {% endif %}
        {% if perms.users.delete_user %}
        <td>
            <a href="#" class="btn btn-outline-danger form-control">Удалить</a>
        </td>
        {% endif %}
        {% if perms.users.set_active %}
        <td>
            <a href="{% url 'user:user_toggle' usr.pk %}"
               class="btn btn-outline-{% if usr.is_active %}danger{% else %}light{% endif %} form-control">
                {% if usr.is_active %}
                Заблокировать
                {% else %}
                Активировать
                {% endif %}
            </a>
        </td>
        {% endif %}
    </tr>
    {% endif %}
    {% endfor %}
</table>
{% endblock %}