config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('user/', include('users.urls', namespace='user')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    MailingAttemptListView, ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    index, BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, set_mailing_status_disregard

app_name = MainConfig.name

urlpatterns = [
    path('', index, name='home'),
    path('mailings/', MailingListView.as_view(), name='mailings'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/new/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/<int:pk>/edit/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('attempts/', MailingAttemptListView.as_view(), name='attempts'),
    path('clients/', ClientListView.as_view(), name='clients'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/new/', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/edit/', ClientUpdateView.as_view(), name='client_edit'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('blog', cache_page(60)(BlogListView.as_view()), name='blog'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/new/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/edit/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
    path('mailings/disregard/<int:mailing_id>/', set_mailing_status_disregard, name='disregard_mailing'),
]

main/models.py
from django.core.cache import cache
from django.db import models

from config import settings
from users.models import User

NULLABLE = {
    'blank': True,
    'null': True
}


class Client(models.Model):
    """
    Модель представляет клиента.

    Атрибуты:
        email (models.EmailField): Электронная почта клиента, обязательное поле, уникальное.
        last_name (models.CharField): Фамилия клиента, обязательное поле, максимальная длина 50 символов.
        first_name (models.CharField): Имя клиента, обязательное поле, максимальная длина 50 символов.
        second_name (models.CharField): Отчество клиента, необязательное поле, максимальная длина 50 символов.
        comment (models.TextField): Комментарий к клиенту, необязательное поле.
        owner (models.ForeignKey): Владелец клиента, связь с моделью пользователя (User), обязательное поле.

    Методы:
        get_full_name(): Возвращает полное имя клиента.
        get_initials(): Возвращает инициалы клиента.
        get_client_owner(): Возвращает владельца клиента.
        get_unique_clients(): Статический метод, возвращает количество уникальных клиентов.
    """

    email = models.EmailField(unique=True, verbose_name='Email')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    second_name = models.CharField(max_length=50, verbose_name='Отчество', **NULLABLE)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='clients')

    def __str__(self):
        """
        Строковое представление объекта Client, возвращает полное имя клиента.

        Возвращает:
            str: Полное имя клиента.
        """

        return self.get_full_name()

    def get_client_owner(self):
        """
        Возвращает владельца клиента.

        Возвращает:
            User: Экземпляр пользователя, являющийся владельцем клиента.
        """

        return self.owner

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def get_full_name(self):
        """
        Возвращает полное имя клиента.

        Возвращает:
            str: Полное имя клиента в формате 'Фамилия Имя Отчество'.
        """

        return f'{self.last_name} {self.first_name} {self.second_name}'

    def get_initials(self):
        """
        Возвращает инициалы клиента.

        Возвращает:
            str: Инициалы клиента в формате 'Фамилия И. О.'.
        """

        return f'{self.last_name} {self.first_name[0]}. {self.second_name[0]}.'

    @staticmethod
    def get_unique_clients():
        """
        Статический метод, возвращает количество уникальных клиентов.

        Возвращает:
            int: Количество уникальных клиентов.
        """

        unique_clients = Client.objects.count()

        if settings.CACHE_ENABLED:
            key = 'unique_clients'
            cache_data = cache.get(key)

            if cache_data is None:
                cache_data = unique_clients
                cache.set(key, cache_data, timeout=60)

            return cache_data

        return unique_clients


class Mailing(models.Model):
    """
    Модель представляет рассылку.

    Перечисления:
        STATUS_CHOICES (list): Список возможных статусов рассылки.
        PERIODICITY_CHOICES (list): Список возможных периодичностей рассылки.

    **Атрибуты:**
        title (models.CharField): Заголовок рассылки, обязательное поле, максимальная длина 255 символов.
        message (models.TextField): Содержание рассылки, обязательное поле.
        status (models.CharField): Статус рассылки, обязательное поле, максимальная длина 10 символов, по умолчанию 'Новый'.
        scheduled_time (models.DateTimeField): Дата и время отправки рассылки, обязательное поле.
        periodicity (models.CharField): Периодичность рассылки, обязательное поле, максимальная длина 15 символов, по умолчанию 'Ежедневно'.
        clients (models.ManyToManyField): Список клиентов, которым будет отправлена рассылка.
        owner (models.ForeignKey): Владелец рассылки, связь с моделью пользователя (User), обязательное поле.

    Методы:
        __str__(): Возвращает заголовок рассылки.
        set_status_disregard(): Устанавливает статус рассылки 'Отклонен' и сохраняет изменения.
        get_total_mailings(): Статический метод, возвращает общее количество рассылок.
        get_active_mailings(): Статический метод, возвращает количество активных рассылок.
    """

    STATUS_CHOICES = [
        ('Новый', 'Новый'),
        ('Отправлен', 'Отправлен'),
        ('Отклонен', 'Отклонен'),
    ]
    PERIODICITY_CHOICES = [
        ('Ежедневно', 'Ежедневно'),
        ('Еженедельно', 'Еженедельно'),
        ('Ежемесячно', 'Ежемесячно'),
    ]

    title = models.CharField(max_length=255, verbose_name='Заголовок рассылки')
    message = models.TextField(verbose_name='Содержание рассылки')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, verbose_name='Статус рассылки', default='Новый')
    scheduled_time = models.DateTimeField(verbose_name='Дата и время отправки')
    periodicity = models.CharField(max_length=15, choices=PERIODICITY_CHOICES, verbose_name='Периодичность расылки',
                                   default='Ежедневно')
    clients = models.ManyToManyField(Client, verbose_name='Клиенты')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mailing')

    def __str__(self):
        """
        Строковое представление объекта Mailing, возвращает заголовок рассылки.

        Возвращает:
            str: Заголовок рассылки.
        """

        return self.title

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

        permissions = [
            (
                'set_status_disregard',
                'Отключение рассылки.'
            )
        ]

    @staticmethod
    def get_total_mailings():
        """
        Возвращает общее количество рассылок.

        Если включено кеширование, данные будут получены из кеша или сохранены в кеш при отсутствии.

        Возвращает:
            int: Общее количество рассылок.
        """

        if settings.CACHE_ENABLED:
            key = 'total_mailings'
            cache_data = cache.get(key)

            if cache_data is None:
                total_mailings = Mailing.objects.count()
                cache_data = total_mailings
                cache.set(key, cache_data, timeout=60)

            return cache_data

        return Mailing.objects.count()

    @staticmethod
    def get_active_mailings():
        """
        Возвращает количество активных рассылок.

        Если включено кеширование, данные будут получены из кеша или сохранены в кеш при отсутствии.

        Возвращает:
            int: Количество активных рассылок.
        """

        if settings.CACHE_ENABLED:
            key = 'active_mailings'
            cache_data = cache.get(key)

            if cache_data is None:
                active_mailings = Mailing.objects.filter(status='Новый').count() + Mailing.objects.filter(
                    status='Отправлен').count()
                cache_data = active_mailings
                cache.set(key, cache_data, timeout=60)

            return cache_data

        return Mailing.objects.filter(status='Новый').count() + Mailing.objects.filter(status='Отправлен').count()

    def set_status_disregard(self):
        """
        Устанавливает статус рассылки 'Отклонен' и сохраняет изменения.
        """

        self.status = 'Отклонен'
        self.save()


class MailingAttempt(models.Model):
    """
    Модель представляет попытку отправки рассылки.

    Атрибуты:
        mailing (models.ForeignKey): Ссылка на модель Mailing, обязательное поле. При удалении рассылки
                                     удаляются и связанные с ней попытки отправки.
        time (models.DateTimeField): Дата и время попытки отправки, устанавливается автоматически при создании.
        status (models.CharField): Статус попытки отправки, обязательное поле, максимальная длина 10 символов.
        log_message (models.TextField): Лог сообщения, дополнительное поле с возможностью быть пустым.
    """

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')
    time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки отправки')
    status = models.CharField(max_length=10, choices=Mailing.STATUS_CHOICES, verbose_name='Статус попытки отправки')
    log_message = models.TextField(verbose_name='Лог сообщения', **NULLABLE)

    def __str__(self):
        """
        Строковое представление объекта MailingAttempt, возвращает информацию о попытке отправки.

        Возвращает:
            str: Информация о попытке отправки рассылки с датой и временем отправки.
        """

        return f'Попытка отправки рассылки {self.mailing.title} на {self.time}'

    def get_mailing_owner(self):
        """
        Возвращает владельца рассылки, к которой относится данная попытка отправки.

        Возвращает:
            User: Владелец рассылки.
        """

        return self.mailing.owner

    class Meta:
        verbose_name = 'Попытка отправки рассылки'
        verbose_name_plural = 'Попытки отправки рассылок'


class BlogPost(models.Model):
    """
    Модель представляет статью блога.

    Атрибуты:
        title (models.CharField): Наименование статьи, обязательное поле, максимальная длина 200 символов.
        content (models.TextField): Содержание статьи, текстовое поле.
        image (models.ImageField): Изображение, дополнительное поле. Поддерживает загрузку изображений
                                   в каталог 'blog_images'. Поле может быть пустым и необязательным.
        view_count (models.PositiveIntegerField): Количество просмотров статьи, поле с положительным числовым значением.

main/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget, AdminTimeWidget

from .models import Mailing, Client


class MailingForm(forms.ModelForm):
    """
    Форма для создания и обновления экземпляров модели Mailing.

    Атрибуты:
        scheduled_time (forms.DateTimeField): Поле для указания даты и времени отправки, отображается как ввод типа
                                              datetime-local.
    """

    scheduled_time = forms.DateTimeField(label='Дата и время отправки',
                                         widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    class Meta:
        model = Mailing
        fields = [
            'title',
            'message',
            'status',
            'scheduled_time',
            'periodicity',
            'clients'
        ]


class ClientForm(forms.ModelForm):
    """
    Форма для создания и обновления экземпляров модели Client.

    Атрибуты (из Meta-класса):
        email (forms.EmailField): Поле для ввода email адреса клиента.
        last_name (forms.CharField): Поле для ввода фамилии клиента.
        first_name (forms.CharField): Поле для ввода имени клиента.
        second_name (forms.CharField): Поле для ввода отчества клиента.
        comment (forms.CharField): Поле для ввода комментария о клиенте.
    """

    class Meta:
        model = Client
        fields = ['email', 'last_name', 'first_name', 'second_name', 'comment']

main/templates/main/blogpost_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <h1>Вы действительно хотите удалить статью {{ object.title }}</h1>
        <form method="post">
            {% csrf_token %}
            <button class="p-2 btn btn-outline-danger" type="submit">Да</button>
            <a class="p-2 btn btn-outline-primary" href="{% url 'main:blog' %}">Нет</a>
        </form>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

main/templates/main/blogpost_detail.html
{% extends 'main/base.html' %}
{% block content %}
{% load custom_filters %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
            </div>
            <div class="card-body">
                {% if object.image %}
                <img src="{{ object.image|media_redirection }}" class="img-fluid" alt="{{ article.title }}">
                {% endif %}
                <p>{{ object.published_date }}</p>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- {{ object.content }}</li>
                </ul>
                <p>Количество просмотров: {{ object.view_count }}</p>
                {% if perms.main.change_blogpost %}
                <a class="p-2 btn btn-outline-warning"
                   href="{% url 'main:blog_edit' object.pk %}">Редактировать</a>
                {% endif %}
                {% if perms.main.delete_blogpost %}
                <a class="p-2 btn btn-outline-danger"
                   href="{% url 'main:blog_delete' object.pk %}">Удалить</a>
                {% endif %}
                <a class="p-2 btn btn-outline-light" href="{% url 'main:blog' %}">Назад</a>
            </div>
        </div>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

main/templates/main/blogpost_list.html
{% extends 'main/base.html' %}
{% block content %}
{% load custom_filters %}
{% if perms.main.add_blogpost %}
<div class="row text-end">
    <div class="col">
        <a type="button" class="btn btn-primary mb-2" href="{% url 'main:blog_create' %}">Добавить статью</a>
    </div>
</div>
{% endif %}
<div class="row">
    {% for article in object_list %}
    <div class="col-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ article.title }}</h4>
            </div>
            <div class="card-body">
                {% if article.image %}
                <img src="{{ article.image|media_redirection }}" class="img-fluid" alt="{{ article.title }}">
                {% endif %}
                <p>{{ article.published_date }}</p>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- {{ article.content|truncatechars:100 }}</li>
                </ul>
                <p>Количество просмотров: {{ article.view_count }}</p>
                <a class="p-2 btn btn-outline-primary"
                   href="{% url 'main:blog_detail' article.pk %}">Подробнее</a>
                {% if perms.main.change_blogpost %}
                <a class="p-2 btn btn-outline-warning"
                   href="{% url 'main:blog_edit' article.pk %}">Редактировать</a>
                {% endif %}
                {% if perms.main.delete_blogpost %}
                <a class="p-2 btn btn-outline-danger"
                   href="{% url 'main:blog_delete' article.pk %}">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="row">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">Первая</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Первая</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#">Предыдущая</a>
            </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <li class="page-item active">
                <a class="page-link" href="#">{{ num }}</a>
            </li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Следующая</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#">Последняя</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container text-center">
    <h2>Вы уверены, что хотите удалить клиента "{{ client }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да, удалить</button>
        <a href="{% url 'main:clients' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

main/templates/main/client_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container">
    <div class="card mb-4 rounded-3 shadow-sm text-center">
        <div class="card-header py-3">
            <h4 class="my-0 fw-normal">{{ client.get_initials }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title">{{ client.get_full_name }}</h1>
            <ul class="list-unstyled mt-3 mb-4">
                <li><strong>Email:</strong> {{ client.email }}</li>
                <li><strong>Комментарии:</strong> {{ client.comment }}</li>
            </ul>
            <a href="{% url 'main:client_edit' client.pk %}" class="btn btn-outline-primary">Редактировать</a>
            <a href="{% url 'main:client_delete' client.pk %}" class="btn btn-outline-danger">Удалить</a>
            <a href="{% url 'main:clients' %}" class="btn btn-outline-secondary">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row text-center">
    <div class="col-4"></div>
    <div class="col-4">
        <h2>{% if form.instance.pk %}Резактирование{% else %}Создание{% endif %} клиента</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary mt-2">Сохранить</button>
            <a href="{% url 'main:clients' %}" class="btn btn-outline-secondary mt-2">Назад</a>
        </form>
    </div>
    <div class="col-4"></div>
</div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}
{% block content %}
<table class="table table-hover">
    {% for client in object_list %}
    {% if client.get_client_owner == user %}
    <tr>
        <td>{{ client.get_initials }}</td>
        <td>{{ client.email }}</td>
        <td>{{ client.comment }}</td>
        <td><a href="{% url 'main:client_detail' client.pk %}" class="btn btn-outline-light form-control">Подробнее</a>
        </td>
        <td><a href="{% url 'main:client_edit' client.pk %}"
               class="btn btn-outline-warning form-control">Редактировать</a></td>
        <td><a href="{% url 'main:client_delete' client.pk %}" class="btn btn-outline-danger form-control">Удалить</a>
        </td>
    </tr>
    {% endif %}
    {% endfor %}
</table>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}
{% load custom_filters %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <p>Количество рассылок всего: {{ total_mailings }}</p>
        <p>Количество активных рассылок: {{ active_mailings }}</p>
        <p>Количество уникальных клиентов для рассылок: {{ unique_clients }}</p>
        <hr>
        <h2>О сервисе</h2>
        <ul>
            <div class="row">
                {% for article in random_articles %}
                <div class="col-3 text-center">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ article.title }}</h4>
                        </div>
                        <div class="card-body">
                            {% if article.image %}
                            <img src="{{ article.image|media_redirection }}" class="img-fluid"
                                 alt="{{ article.title }}">
                            {% endif %}
                            <p>{{ article.published_date }}</p>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>- {{ article.content|truncatechars:100 }}</li>
                            </ul>
                            <p>Количество просмотров: {{ article.view_count }}</p>
                            <a class="p-2 btn btn-outline-primary"
                               href="{% url 'main:blog_detail' article.pk %}">Подробнее</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </ul>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

main/templates/main/mailing_attempt_list.html
{% extends 'main/base.html' %}
{% block content %}
<table class="table table-hover">
    <tr>
        <th class="text-center">Рассылка</th>
        <th class="text-center">Дата и время попытки отправки</th>
        <th class="text-center">Статус попытки отправки</th>
        <th class="text-center">Сообщение при отправке</th>
    </tr>
    {% for mailing in mailings_attempts %}
    {% if mailing.get_mailing_owner == user %}
    <tr>
        <td class="text-center">{{ mailing.mailing }}</td>
        <td class="text-center">{{ mailing.time }}</td>
        <td class="text-center">{{ mailing.status }}</td>
        <td class="text-center">{{ mailing.log_message }}</td>
    </tr>
    {% endif %}
    {% endfor %}
</table>
{% endblock %}

main/templates/main/mailing_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container text-center">
    <h2>Вы уверены, что хотите удалить рассылку "{{ mailing }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да, удалить</button>
        <a href="{% url 'main:mailings' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

main/templates/main/mailing_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container">
    <div class="card mb-4 rounded-3 shadow-sm text-center">
        <div class="card-header py-3">
            <h4 class="my-0 fw-normal">{{ mailing.title }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title">{{ mailing.message }}</h1>
            <ul class="list-unstyled mt-3 mb-4">
                <li><strong>Статус рассылки:</strong> {{ mailing.status }}</li>
                <li><strong>Дата и время начала рассылки:</strong> {{ mailing.scheduled_time }}</li>
                <li><strong>Периодичность рассылки:</strong> {{ mailing.periodicity }}</li>
                <li><strong>Клиенты:</strong> {% for client in mailing.clients.all %}{{ client.get_initials }}
                    ({{ client.email }})</br>{% endfor %}
                </li>
                <li><strong>Влыделец:</strong> {{ mailing.owner }}</li>
            </ul>
            {% if mailing.owner == user or perms.main.change_mailing %}
            <a href="{% url 'main:mailing_edit' mailing.pk %}" class="btn btn-outline-primary">Редактировать</a>
            {% endif %}
            {% if mailing.owner == user or perms.main.delete_mailing %}
            <a href="{% url 'main:mailing_delete' mailing.pk %}" class="btn btn-outline-danger">Удалить</a>
            {% endif %}
            {% if perms.main.set_status_disregard and mailing.status != 'Отклонен' %}
            <td>
                <a href="{% url 'main:disregard_mailing' mailing.pk %}" class="btn btn-outline-danger">
                    Отключить</a>
            </td>
            {% endif %}
            <a href="{% url 'main:mailings' %}" class="btn btn-outline-secondary">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/mailing_form.html
{% extends 'main/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row text-center">
    <div class="col-4"></div>
    <div class="col-4">
        <h2>{% if form.instance.pk %}Резактирование{% else %}Создание{% endif %} рассылки</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary mt-2">Сохранить</button>
            <a href="{% url 'main:mailings' %}" class="btn btn-outline-secondary mt-2">Назад</a>
        </form>
    </div>
    <div class="col-4"></div>
</div>
{% endblock %}

main/templates/main/mailing_list.html
{% extends 'main/base.html' %}
{% block content %}
<table class="table table-hover">
    {% for mailing in mailings %}
    {% if mailing.owner == user or perms.main.view_mailing %}
    <tr>
        <td class="text-end">
            <a href="{% url 'main:mailing_detail' mailing.pk %}" class="action">{{ mailing.title }} -
                {{mailing.scheduled_time|date:"DATETIME_FORMAT" }}</a>
        </td>
        {% if mailing.owner == user or perms.main.change_mailing %}
        <td>
            <a href="{% url 'main:mailing_edit' mailing.pk %}"
               class="btn btn-outline-light form-control">Редактировать</a>
        </td>
        {% endif %}
        {% if mailing.owner == user or perms.main.delete_mailing %}
        <td>
            <a href="{% url 'main:mailing_delete' mailing.pk %}" class="btn btn-outline-danger form-control">Удалить</a>
        </td>
        {% endif %}
        {% if perms.main.set_status_disregard and mailing.status != 'Отклонен' %}
        <td>
            <a href="{% url 'main:disregard_mailing' mailing.pk %}" class="btn btn-outline-danger form-control">
                Отключить</a>
        </td>
        {% endif %}
    </tr>
    {% endif %}
    {% endfor %}
</table>
{% endblock %}